kind: Service
apiVersion: v1
metadata:
  name: {{ include "mayan.fullname" . }}-frontend
  labels:
    {{- include "mayan.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  ports:
    - name: http
      port: 8000
      protocol: TCP
  selector:
    {{- include "mayan.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  type: {{ .Values.frontend.service.type | default "ClusterIP" }}

